### ISSUE TITLE
[QUESTION] Concurrent Recording 

### ISSUE THREAD

**Issue by GuyPerets106** [raspberrypi/rpicam-apps#617]
Hi , I'm using a RPi 5 (8GB RAM) and connecting x2 Camera Module 3 Wide to it. 
Wanted to ask if there's a way to start a recording at both cameras with one terminal command. 
Currently I'm executing 2 different commands with `--camera 0` and `--camera 1`.
I'm trying to record as synced as possible between the cameras so I'm using cpp to execute this commands with pthreads , but it's not ideal. 

So there's a way to run something like `rpicam-vid --camera all -o test.h264` or something similar?
Thanks!

**Comment by naushir** [comment]
Unfortunately there is no possibility of hardware based camera sync for Camera Module 3 as the pins just don't exist.  This means that any "local" software sync through multiple threads/instances is just not going to work well.

We are considering if/how we can add some sort of control loop so that we can remotely sink cameras in some way.   If it works, it would be very cool because we could plausibly sync any number of cameras as long as they are connected to the same local network. However this is very very early thoughts, so nothing really to discuss just yet.
